export const SET_VIDEOS = "SET_VIDEOS";
export const TOGGLE_VIDEO_FETCHING_STATE = "TOGGLE_VIDEO_FETCHING_STATE";

// for playlist
export const SET_PLAYLIST = "SET_PLAYLIST";
export const TOGGLE_PLAYLIST_FETCHING_STATE = "TOGGLE_PLAYLIST_FETCHING_STATE";

// for fetching current video on click
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";
export const TOGGLE_CURRENT_VIDEO_FETCHING_STATE = "TOGGLE_CRRENT_VIDEO_FETCHING_STATE";

export const SET_COMMENTS = "SET_COMMENTS";

export const SET_USER = "SET_USER";
export const TOGGLE_AUTH_STATE = "TOGGLE_AUTH_STATE";

export const LOGOUT_USER = "LOGOUT_USER";